import type {
  Category,
  CodingPlan,
  DashboardStats,
  ModelPrice,
  ModelRanking,
  RelayEvaluation,
  Resource,
  SourceLink,
  Submission,
} from "./types";

export const sourceLinks: SourceLink[] = [
  {
    name: "知乎 Coding Plan 对比",
    url: "https://zhuanlan.zhihu.com/p/2015468530938693485",
    description: "国内外 AI Coding 订阅与额度口径参考。",
  },
  {
    name: "awesome-coding-plan",
    url: "https://github.com/mahonzhan/awesome-coding-plan",
    description: "Cursor、Claude Code、Trae、Qoder、Windsurf 等计划对比。",
  },
  {
    name: "LiteLLM model prices",
    url: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    description: "模型输入/输出价格与上下文窗口。",
  },
  {
    name: "Arena Leaderboard",
    url: "https://arena.ai/leaderboard",
    description: "用户偏好投票驱动的大模型榜单。",
  },
  {
    name: "SuperCLUE",
    url: "https://www.superclueai.com/generalpage",
    description: "中文大模型综合能力与应用能力榜单。",
  },
  {
    name: "禾维 AI",
    url: "https://www.hvoy.ai/leaderboard/",
    description: "中转站价格、延迟、在线率、掺水率与模型验证参考。",
  },
  {
    name: "AI 比价",
    url: "https://www.aibijia.org/",
    description: "ChatGPT、Gemini、Claude Code、Grok 等代充比价入口。",
  },
  {
    name: "TelegramGroup",
    url: "https://github.com/itgoyo/TelegramGroup",
    description: "Telegram 群组与频道导航开源集合。",
  },
];

export const categories: Category[] = [
  {
    id: "cat-coding",
    key: "coding",
    name: "Coding Plan 对比",
    description: "订阅价格、额度口径、模型倍率和 API 成本",
    iconName: "Code2",
    sortOrder: 1,
    count: 9,
  },
  {
    id: "cat-leaderboard",
    key: "leaderboard",
    name: "大模型排行",
    description: "Arena、SuperCLUE 与代码能力综合排序",
    iconName: "Trophy",
    sortOrder: 2,
    count: 10,
  },
  {
    id: "cat-relay",
    key: "relay",
    name: "中转站导航",
    description: "价格、在线率、延迟、掺水率和模型覆盖",
    iconName: "Network",
    sortOrder: 3,
    count: 8,
  },
  {
    id: "cat-topup",
    key: "topup",
    name: "代充站导航",
    description: "订阅代充、比价、服务范围和风险提示",
    iconName: "WalletCards",
    sortOrder: 4,
    count: 6,
  },
  {
    id: "cat-telegram",
    key: "telegram",
    name: "飞机频道导航",
    description: "AI 工具、开发、搜索与资源频道",
    iconName: "Send",
    sortOrder: 5,
    count: 7,
  },
  {
    id: "cat-validation",
    key: "validation",
    name: "模型验证评价",
    description: "中转站模型响应质量、原生度与稳定性记录",
    iconName: "ShieldCheck",
    sortOrder: 6,
    count: 6,
  },
];

export const resources: Resource[] = [
  {
    id: "res-hvoy",
    name: "禾维 AI 中转站排行榜",
    categoryKey: "relay",
    url: "https://www.hvoy.ai/leaderboard/",
    description: "按模型收录中转站价格、在线率、掺水率、延迟和运行状态。",
    tags: ["价格", "在线率", "掺水率", "延迟"],
    region: "国内",
    status: "active",
    score: 4.9,
    visits: 26800,
    latencyMs: 165,
    uptime: 99.3,
    waterRate: 0.6,
    pricingNote: "按模型与站点倍率展示",
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/leaderboard/",
    models: ["Claude", "GPT", "Gemini", "DeepSeek", "Qwen"],
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-hvoy-validation",
    name: "禾维 AI 模型验证",
    categoryKey: "validation",
    url: "https://www.hvoy.ai/",
    description: "对中转站模型进行可用性、原生度、延迟和质量复测。",
    tags: ["模型验证", "原生度", "质量评分"],
    region: "国内",
    status: "active",
    score: 4.8,
    visits: 15200,
    latencyMs: 178,
    uptime: 98.9,
    waterRate: 1.1,
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/",
    models: ["Claude Sonnet", "GPT-5.4", "Gemini Pro"],
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-litellm",
    name: "LiteLLM 模型价格库",
    categoryKey: "coding",
    url: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    description: "开源模型价格与上下文窗口数据库，适合做 API 价格基准。",
    tags: ["API 价格", "上下文", "开源"],
    region: "全球",
    status: "active",
    score: 4.9,
    visits: 18900,
    sourceName: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    models: ["OpenAI", "Anthropic", "Google", "DeepSeek", "Moonshot"],
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-awesome-coding",
    name: "awesome-coding-plan",
    categoryKey: "coding",
    url: "https://github.com/mahonzhan/awesome-coding-plan",
    description: "对比 Coding Agent 订阅计划、额度周期、模型倍率和性价比。",
    tags: ["Coding Agent", "订阅", "额度"],
    region: "全球",
    status: "active",
    score: 4.8,
    visits: 12600,
    sourceName: "GitHub",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-arena",
    name: "Arena Leaderboard",
    categoryKey: "leaderboard",
    url: "https://arena.ai/leaderboard",
    description: "基于用户偏好投票的文本、代码、推理模型榜单。",
    tags: ["Arena", "用户投票", "模型排行"],
    region: "海外",
    status: "active",
    score: 4.9,
    visits: 52200,
    sourceName: "Arena",
    sourceUrl: "https://arena.ai/leaderboard",
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-superclue",
    name: "SuperCLUE",
    categoryKey: "leaderboard",
    url: "https://www.superclueai.com/generalpage",
    description: "中文大模型综合能力、应用能力与多维评测榜单。",
    tags: ["中文评测", "综合能力", "应用能力"],
    region: "国内",
    status: "active",
    score: 4.6,
    visits: 30800,
    sourceName: "SuperCLUE",
    sourceUrl: "https://www.superclueai.com/generalpage",
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-aibijia",
    name: "AI 比价",
    categoryKey: "topup",
    url: "https://www.aibijia.org/",
    description: "聚合 ChatGPT、Gemini、Claude Code、Grok 等订阅代充比价。",
    tags: ["ChatGPT", "Gemini", "Claude Code", "Grok"],
    region: "国内",
    status: "active",
    score: 4.7,
    visits: 21300,
    pricingNote: "展示各服务商报价，交易前需自行核验",
    sourceName: "AI 比价",
    sourceUrl: "https://www.aibijia.org/",
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-telegramgroup",
    name: "TelegramGroup",
    categoryKey: "telegram",
    url: "https://github.com/itgoyo/TelegramGroup",
    description: "开源 Telegram 群组频道合集，覆盖搜索、资源、技术和工具分类。",
    tags: ["Telegram", "频道", "开源索引"],
    region: "全球",
    status: "active",
    score: 4.3,
    visits: 18100,
    sourceName: "TelegramGroup",
    sourceUrl: "https://github.com/itgoyo/TelegramGroup",
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-soso",
    name: "soso 搜索机器人",
    categoryKey: "telegram",
    url: "https://t.me/soso",
    description: "Telegram 搜索入口，适合快速发现频道、群组和公开资源。",
    tags: ["搜索", "机器人", "频道发现"],
    region: "全球",
    status: "active",
    score: 4.1,
    visits: 8600,
    sourceName: "TelegramGroup",
    sourceUrl: "https://github.com/itgoyo/TelegramGroup",
  },
  {
    id: "res-technews",
    name: "科技圈的日常",
    categoryKey: "telegram",
    url: "https://t.me/kejijun",
    description: "科技资讯、AI 工具与开发者新闻频道。",
    tags: ["资讯", "AI 工具", "开发"],
    region: "全球",
    status: "active",
    score: 4.0,
    visits: 7200,
    sourceName: "TelegramGroup",
    sourceUrl: "https://github.com/itgoyo/TelegramGroup",
  },
];

export const codingPlans: CodingPlan[] = [
  {
    id: "plan-core-01-claude-pro",
    section: "core",
    vendor: "Claude Pro",
    planName: "Claude Pro",
    modelName: "Claude Code claude-sonnet-4.6",
    monthlyPrice: "$20.00（AppStore尼日利亚~$11.09)",
    officialNote: "",
    note: "(Claude Code claude-sonnet-4.6)",
    tps: "/",
    requestsTokens5h: "298/529万",
    value5h: "$4.06",
    ratio5h: "0.20",
    requestsTokensWeek: "2709/4809万",
    valueWeek: "$36.91",
    ratioWeek: "1.85",
    requestsTokensMonth: "10836/1.92亿",
    valueMonth: "$147.64",
    ratioMonth: "7.38",
    officialUrl: "https://claude.ai/upgrade",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 1,
  },
  {
    id: "plan-core-02-chatgpt-plus",
    section: "core",
    vendor: "ChatGPT Plus",
    planName: "ChatGPT Plus",
    modelName: "Codex gpt-5.4",
    monthlyPrice: "$20.00（AppStore土耳其~$11.14，Team拼车最便宜）",
    officialNote: "45-225 Local Messages* / 5h",
    note: "(Codex gpt-5.4)",
    tps: "/",
    requestsTokens5h: "490/2000万",
    value5h: "$11.85",
    ratio5h: "0.59",
    requestsTokensWeek: "3062/1.2亿",
    valueWeek: "$74",
    ratioWeek: "3.7",
    requestsTokensMonth: "12250/4.8亿",
    valueMonth: "$296",
    ratioMonth: "14.8",
    officialUrl: "https://chatgpt.com/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 2,
  },
  {
    id: "plan-core-03-openrouter",
    section: "core",
    vendor: "OpenRouter",
    planName: "OpenRouter",
    monthlyPrice: "部分模型限免",
    officialNote: "hy3-preview/minimax-m2.5/qwen3-coder 限免",
    officialUrl: "https://openrouter.ai",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 3,
  },
  {
    id: "plan-core-04-ollama-free",
    section: "core",
    vendor: "Ollama Free",
    planName: "Ollama Free",
    modelName: "minimax-m2.7",
    monthlyPrice: "免费",
    officialNote: "glm-4.7/minimax-m2.7/qwen3.5 预估费用可能有水份，因为测试发现 cache 并未生效",
    note: "(minimax-m2.7)",
    tps: "/",
    requestsTokens5h: "453/1234万",
    value5h: "$4.19",
    ratio5h: "/",
    requestsTokensWeek: "1365/3716万",
    valueWeek: "$12.62",
    ratioWeek: "/",
    requestsTokensMonth: "5460/1.48亿",
    valueMonth: "$50.48",
    ratioMonth: "/",
    officialUrl: "https://ollama.com/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 4,
  },
  {
    id: "plan-core-05-nvidia-nim",
    section: "core",
    vendor: "NVIDIA NIM",
    planName: "NVIDIA NIM",
    modelName: "glm-4.7",
    monthlyPrice: "免费",
    officialNote: "glm-5.1/glm-4.7/minimax-m2.7 等开源模型 Up to 40 rpm 不限量使用",
    note: "(glm-4.7)",
    officialUrl: "https://build.nvidia.com",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 5,
  },
  {
    id: "plan-core-06-minimax-coding-plan-plus",
    section: "core",
    vendor: "MiniMax Coding Plan Plus",
    planName: "MiniMax Coding Plan Plus",
    modelName: "minimax-m2.7",
    monthlyPrice: "￥49.00",
    officialNote: "1500次模型调用 / 5 小时",
    note: "（minimax-m2.7）",
    tps: "52.6",
    requestsTokens5h: "1360/6000万",
    value5h: "￥108.60",
    ratio5h: "2.22",
    requestsTokensWeek: "13600/6亿",
    valueWeek: "￥1086",
    ratioWeek: "22.2",
    requestsTokensMonth: "54400/24亿",
    valueMonth: "￥4344",
    ratioMonth: "88.65",
    officialUrl: "https://platform.minimaxi.com/subscribe/token-plan",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 6,
  },
  {
    id: "plan-core-07-kimi-code-andante",
    section: "core",
    vendor: "Kimi Code Andante",
    planName: "Kimi Code Andante",
    modelName: "kimi-k2.5",
    monthlyPrice: "￥49.00",
    officialNote: "Kimi Code 可调用",
    note: "（kimi-k2.5）",
    tps: "20.1",
    requestsTokens5h: "359/1500万",
    value5h: "￥21.46",
    ratio5h: "0.44",
    requestsTokensWeek: "639/2100万",
    valueWeek: "￥30.34",
    ratioWeek: "0.62",
    requestsTokensMonth: "2556/8400万",
    valueMonth: "￥121.36",
    ratioMonth: "2.48",
    officialUrl: "https://www.kimi.com/membership/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 7,
  },
  {
    id: "plan-core-08-kimi-code-allegretto",
    section: "core",
    vendor: "Kimi Code Allegretto",
    planName: "Kimi Code Allegretto",
    modelName: "kimi-k2.5",
    monthlyPrice: "￥199.00",
    officialNote: "Kimi Code 20 倍额度",
    note: "（kimi-k2.5）",
    tps: "20.1",
    requestsTokens5h: "1307/6500万",
    value5h: "￥89.67",
    ratio5h: "0.45",
    requestsTokensWeek: "9073/3.57亿",
    valueWeek: "￥492.00",
    ratioWeek: "2.47",
    requestsTokensMonth: "36292/14.28亿",
    valueMonth: "￥1,968.00",
    ratioMonth: "9.89",
    officialUrl: "https://www.kimi.com/membership/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 8,
  },
  {
    id: "plan-core-09-aliyun-coding-plan-lite",
    section: "core",
    vendor: "阿里云 Coding Plan Lite 基础套餐",
    planName: "阿里云 Coding Plan Lite 基础套餐",
    modelName: "qwen-3.5-plus",
    monthlyPrice: "￥40.00",
    officialNote: "每月请求额度至高 18,000 次 最多 1,200 次/每 5 小时 最多 9,000 次/每周 最多 18,000 次/每月",
    note: "（已下线, qwen-3.5-plus）",
    tps: "52.5",
    requestsTokens5h: "1179/4000万",
    value5h: "￥52.83",
    ratio5h: "1.32",
    requestsTokensWeek: "8842/3亿",
    valueWeek: "￥396.00",
    ratioWeek: "9.90",
    requestsTokensMonth: "17684/6亿",
    valueMonth: "￥792.00",
    ratioMonth: "19.80",
    officialUrl: "https://www.aliyun.com/benefit/scene/codingplan",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 9,
  },
  {
    id: "plan-core-10-volcengine-coding-plan-lite",
    section: "core",
    vendor: "火山方舟 Coding Plan Lite",
    planName: "火山方舟 Coding Plan Lite",
    modelName: "doubao-seed-2.0-pro",
    monthlyPrice: "￥40.00",
    officialNote: "数倍于 Claude Pro plan 的用量",
    note: "（doubao-seed-2.0-pro）",
    tps: "86.6",
    requestsTokens5h: "148/1000万",
    value5h: "￥19.00",
    ratio5h: "0.48",
    requestsTokensWeek: "1138/7500万",
    valueWeek: "￥146.00",
    ratioWeek: "3.65",
    requestsTokensMonth: "6275/3.2亿",
    valueMonth: "￥607.00",
    ratioMonth: "15.18",
    officialUrl: "https://www.volcengine.com/activity/codingplan",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 10,
  },
  {
    id: "plan-core-11-glm-coding-plan-lite",
    section: "core",
    vendor: "GLM Coding Plan Lite",
    planName: "GLM Coding Plan Lite",
    modelName: "glm-5.1",
    monthlyPrice: "￥49.00",
    officialNote: "3x Claude Pro 用量额度 每 5 小时限额 最多约 80 次 prompts 每周限额 最多约 400 次 prompts",
    note: "（使用海外版订阅测试 glm-5.1）",
    tps: "26.8",
    requestsTokens5h: "90/600万",
    value5h: "￥11.66",
    ratio5h: "0.24",
    requestsTokensWeek: "600/3200万",
    valueWeek: "￥62.19",
    ratioWeek: "1.27",
    requestsTokensMonth: "2400/1.28亿",
    valueMonth: "￥248.76",
    ratioMonth: "5.08",
    officialUrl: "https://bigmodel.cn/glm-coding",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 11,
  },
  {
    id: "plan-core-12-glm-coding-plan-pro",
    section: "core",
    vendor: "GLM Coding Plan Pro",
    planName: "GLM Coding Plan Pro",
    modelName: "glm-5.1",
    monthlyPrice: "￥149.00",
    officialNote: "5x Lite 用量额度 最多约 400 次 prompts 最多约 2000 次 prompts",
    note: "（glm-5.1）",
    tps: "26.8",
    requestsTokens5h: "450/3000万",
    value5h: "￥58.3",
    ratio5h: "0.39",
    requestsTokensWeek: "3000/1.6亿",
    valueWeek: "￥310.95",
    ratioWeek: "2.09",
    requestsTokensMonth: "12000/6.4亿",
    valueMonth: "￥1243.8",
    ratioMonth: "8.35",
    officialUrl: "https://bigmodel.cn/glm-coding",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 12,
  },
  {
    id: "plan-core-13-fireworks-fire-pass",
    section: "core",
    vendor: "Fireworks Fire Pass",
    planName: "Fireworks Fire Pass",
    modelName: "kimi-k2.5-turbo",
    monthlyPrice: "$7/w*4",
    officialNote: "with no per-token charges for kimi-k2.5-turbo",
    note: "（kimi-k2.5-turbo）",
    officialUrl: "https://app.fireworks.ai/fire-pass",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 13,
  },
  {
    id: "plan-core-14-xiaomi-mimo-token-plan-lite",
    section: "core",
    vendor: "Xiaomi MiMo Token Plan Lite",
    planName: "Xiaomi MiMo Token Plan Lite",
    monthlyPrice: "￥39.00",
    officialNote: "60,000,000 Credits 套餐月总量 MiMo-V2.5-Pro 256k 上下文： 2x（消耗 1 Token = 2 Credits）",
    note: "（非实测数据）",
    requestsTokens5h: "/",
    value5h: "/",
    ratio5h: "/",
    requestsTokensWeek: "/",
    valueWeek: "/",
    ratioWeek: "/",
    requestsTokensMonth: "?/3000万",
    valueMonth: "?",
    ratioMonth: "?",
    officialUrl: "https://platform.xiaomimimo.com/#/token-plan",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 14,
  },
  {
    id: "plan-ide-01-factory-droid-pro",
    section: "ide-cli",
    vendor: "Factory Droid Pro",
    planName: "Factory Droid Pro",
    monthlyPrice: "$20.00",
    officialNote: "20 million Standard Tokens (10 cached tokens = 1 Standard Token)",
    note: "Usage-based",
    usageType: "Usage-based",
    requestsTokensMonth: "~$48/~6000万 claude-opus-4.6",
    valueMonth: "~$48/~6000万 claude-opus-4.6",
    ratioMonth: "~2.4",
    officialUrl: "https://factory.ai/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 101,
  },
  {
    id: "plan-ide-02-cursor-pro",
    section: "ide-cli",
    vendor: "Cursor Pro",
    planName: "Cursor Pro",
    monthlyPrice: "$20.00",
    officialNote: "$20 of API usage each month Significantly more included usage when Auto or Composer 2 is selected",
    note: "Usage-based",
    usageType: "Usage-based",
    requestsTokensMonth: ">=$20",
    valueMonth: ">=$20",
    ratioMonth: ">=1",
    officialUrl: "https://cursor.com/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 102,
  },
  {
    id: "plan-ide-03-windsurf-pro",
    section: "ide-cli",
    vendor: "Windsurf Pro",
    planName: "Windsurf Pro",
    monthlyPrice: "$20.00 (2 week free trial)",
    officialNote: "plan includes a usage allowance measured as a daily and weekly budget, daily quota is more than 1/7 of your weekly quota 8-101 messages / day for Premium Model unlimited SWE-1.5",
    note: "Quota-based",
    usageType: "Quota-based",
    officialUrl: "https://windsurf.com/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 103,
  },
  {
    id: "plan-ide-04-augment-code-indie",
    section: "ide-cli",
    vendor: "Augment Code INDIE",
    planName: "Augment Code INDIE",
    monthlyPrice: "$20.00",
    officialNote: "Includes 40,000 credits",
    note: "Usage-based",
    usageType: "Usage-based",
    requestsTokensMonth: "$25.00",
    valueMonth: "$25.00",
    ratioMonth: "1.25",
    officialUrl: "https://www.augmentcode.com/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 104,
  },
  {
    id: "plan-ide-05-kiro-pro",
    section: "ide-cli",
    vendor: "Kiro Pro",
    planName: "Kiro Pro",
    monthlyPrice: "$20.00",
    officialNote: "1,000 credits Pay-per-use overage ($0.04/credit) Get 500 bonus credits usable within 30 days when you first sign up",
    note: "Task-based",
    usageType: "Task-based",
    requestsTokensMonth: "$40.00",
    valueMonth: "$40.00",
    ratioMonth: "2",
    officialUrl: "https://kiro.dev/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 105,
  },
  {
    id: "plan-ide-06-qoder-pro",
    section: "ide-cli",
    vendor: "Qoder Pro",
    planName: "Qoder Pro",
    monthlyPrice: "$20.00（限时 50% 折扣）",
    officialNote: "2,000 Credits 更多的对话与智能体请求数 为期 2 周的 Pro 试用及 300 Credits",
    note: "Usage-based",
    usageType: "Usage-based",
    officialUrl: "https://qoder.com/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 106,
  },
  {
    id: "plan-ide-07-antigravity-google-ai-pro",
    section: "ide-cli",
    vendor: "Antigravity Google AI Pro",
    planName: "Antigravity Google AI Pro",
    monthlyPrice: "$19.99（Pixel 手机用户免费试用一年）",
    officialNote: "High, generous quota, refreshed every five hours until weekly limit reached Higher weekly rate limit Free: 50 AI credits/d Google AI Plus $7.99: 200 AI credits/mo Google AI Pro $19.99: 1,000 AI credits/mo Google AI Ultra $249.99: 25,000 AI credits/mo",
    note: "Quota-based",
    usageType: "Quota-based",
    officialUrl: "https://antigravity.google/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 107,
  },
  {
    id: "plan-ide-08-kilo-pass-starter",
    section: "ide-cli",
    vendor: "Kilo Pass Starter",
    planName: "Kilo Pass Starter",
    monthlyPrice: "$19.00",
    officialNote: "Up to 40% bonus credits",
    note: "Usage-based",
    usageType: "Usage-based",
    requestsTokensMonth: "~$26.6",
    valueMonth: "~$26.6",
    ratioMonth: "1.4",
    officialUrl: "https://kilo.ai/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 108,
  },
  {
    id: "plan-ide-09-opencode-go",
    section: "ide-cli",
    vendor: "OpenCode Go",
    planName: "OpenCode Go",
    monthlyPrice: "$10.00 (首月 $5)",
    officialNote: "$12.00/5h $30.00/w $60.00/mo 包含 GLM-5.1, GLM-5, Kimi K2.5, MiMo-V2-Pro, MiMo-V2-Omni, MiniMax M2.5 和 MiniMax M2.7",
    note: "Quota-based",
    usageType: "Quota-based",
    requestsTokensMonth: "$60.00",
    valueMonth: "$60.00",
    ratioMonth: "6",
    officialUrl: "https://opencode.ai/go",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 109,
  },
  {
    id: "plan-ide-10-github-copilot-pro",
    section: "ide-cli",
    vendor: "GitHub Copilot Pro",
    planName: "GitHub Copilot Pro",
    monthlyPrice: "$10.00 Temporarilly unavailable",
    officialNote: "300 premium requests to use latest models, with the option to buy more Unlimited agent mode and chats with GPT-5 mini2 Unlimited inline suggestions",
    note: "1x 模型每条消息 $0.04，$12 内免费，Message-based",
    usageType: "1x 模型每条消息 $0.04，$12 内免费，Message-based",
    requestsTokensMonth: ">>$12",
    valueMonth: ">>$12",
    ratioMonth: ">>1.2",
    officialUrl: "https://github.com/features/copilot/plans",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 110,
  },
  {
    id: "plan-ide-11-zed-pro",
    section: "ide-cli",
    vendor: "Zed Pro",
    planName: "Zed Pro",
    monthlyPrice: "$10.00",
    officialNote: "Unlimited edit predictions $5 of tokens included Usage-based billing beyond $5 14-day free trial. No credit card required.",
    note: "Usage-based",
    usageType: "Usage-based",
    requestsTokensMonth: "$5.00/440万 Claude Sonnet 4.6",
    valueMonth: "$5.00/440万 Claude Sonnet 4.6",
    ratioMonth: "0.5",
    officialUrl: "https://zed.dev/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 111,
  },
  {
    id: "plan-ide-12-trae-pro",
    section: "ide-cli",
    vendor: "Trae Pro",
    planName: "Trae Pro",
    monthlyPrice: "$10.00",
    officialNote: "$20 Basic usage + Bonus usage Unlimited Autocomplete Free for 7 days.",
    note: "Usage-based",
    usageType: "Usage-based",
    requestsTokensMonth: "$20.00",
    valueMonth: "$20.00",
    ratioMonth: "2",
    officialUrl: "https://www.trae.ai/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 112,
  },
  {
    id: "plan-ide-13-codebuddy-pro",
    section: "ide-cli",
    vendor: "CodeBuddy 个人专业版",
    planName: "CodeBuddy 个人专业版",
    monthlyPrice: "￥59.00",
    officialNote: "每月 2000 Credits（含体验版 500 Credits）",
    note: "Usage-based",
    usageType: "Usage-based",
    officialUrl: "https://www.codebuddy.cn/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    sortOrder: 113,
  },
];

export const modelPrices: ModelPrice[] = [
  {
    id: "price-gpt-55",
    provider: "OpenAI",
    model: "GPT-5.5",
    inputUsdPer1M: 5,
    outputUsdPer1M: 30,
    context: "1,050K",
    maxOutput: "128K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-gpt-54",
    provider: "OpenAI / Azure",
    model: "GPT-5.4",
    inputUsdPer1M: 2.5,
    outputUsdPer1M: 15,
    context: "1,050K",
    maxOutput: "128K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-claude-opus-47",
    provider: "Anthropic / OpenRouter",
    model: "Claude Opus 4.7",
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    context: "1,000K",
    maxOutput: "128K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-claude-sonnet-46",
    provider: "Anthropic / OpenRouter",
    model: "Claude Sonnet 4.6",
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    context: "1,000K",
    maxOutput: "128K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-gemini-31",
    provider: "Google",
    model: "Gemini 3.1 Pro Preview",
    inputUsdPer1M: 2,
    outputUsdPer1M: 12,
    context: "1,048K",
    maxOutput: "65K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-kimi-k26",
    provider: "Moonshot",
    model: "Kimi K2.6",
    inputUsdPer1M: 0.95,
    outputUsdPer1M: 4,
    context: "262K",
    maxOutput: "262K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-deepseek-v32",
    provider: "DeepSeek",
    model: "DeepSeek V3.2",
    inputUsdPer1M: 0.28,
    outputUsdPer1M: 0.42,
    context: "128K",
    maxOutput: "8K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
];

export const modelRankings: ModelRanking[] = [
  {
    id: "rank-claude-opus-thinking",
    rank: 1,
    model: "Claude Opus 4.7 Thinking",
    provider: "Anthropic",
    arenaScore: 1503,
    codeScore: 1572,
    chineseScore: 92,
    reasoningScore: 97,
    context: "1M",
    source: "Arena",
    sourceUrl: "https://arena.ai/leaderboard",
    badge: "综合第一梯队",
  },
  {
    id: "rank-claude-opus-46",
    rank: 2,
    model: "Claude Opus 4.6",
    provider: "Anthropic",
    arenaScore: 1496,
    codeScore: 1545,
    chineseScore: 91,
    reasoningScore: 96,
    context: "1M",
    source: "Arena",
    sourceUrl: "https://arena.ai/leaderboard",
    badge: "代码强项",
  },
  {
    id: "rank-gemini-31",
    rank: 3,
    model: "Gemini 3.1 Pro Preview",
    provider: "Google",
    arenaScore: 1493,
    codeScore: 1468,
    chineseScore: 94,
    reasoningScore: 95,
    context: "1M",
    source: "综合",
    sourceUrl: "https://arena.ai/leaderboard",
    badge: "长上下文",
  },
  {
    id: "rank-gpt-55",
    rank: 4,
    model: "GPT-5.5",
    provider: "OpenAI",
    arenaScore: 1490,
    codeScore: 1501,
    chineseScore: 93,
    reasoningScore: 96,
    context: "1M",
    source: "Arena",
    sourceUrl: "https://arena.ai/leaderboard",
    badge: "推理稳定",
  },
  {
    id: "rank-qwen36",
    rank: 5,
    model: "Qwen3.6 Plus",
    provider: "阿里巴巴",
    arenaScore: 1471,
    codeScore: 1471,
    chineseScore: 96,
    reasoningScore: 92,
    context: "128K",
    source: "SuperCLUE",
    sourceUrl: "https://www.superclueai.com/generalpage",
    badge: "中文强项",
  },
  {
    id: "rank-kimi",
    rank: 6,
    model: "Kimi K2.6",
    provider: "月之暗面",
    arenaScore: 1466,
    codeScore: 1529,
    chineseScore: 95,
    reasoningScore: 91,
    context: "256K",
    source: "SuperCLUE",
    sourceUrl: "https://www.superclueai.com/generalpage",
    badge: "代码与中文",
  },
  {
    id: "rank-deepseek",
    rank: 7,
    model: "DeepSeek V3.2",
    provider: "DeepSeek",
    arenaScore: 1458,
    codeScore: 1463,
    chineseScore: 94,
    reasoningScore: 90,
    context: "128K",
    source: "综合",
    sourceUrl: "https://arena.ai/leaderboard",
    badge: "高性价比",
  },
];

export const relayEvaluations: RelayEvaluation[] = [
  {
    id: "eval-hvoy-claude-opus",
    relayName: "禾维收录站点 A",
    model: "Claude Opus 4.7",
    endpoint: "OpenAI Compatible",
    latencyMs: 168,
    availability: 99.3,
    waterRate: 0.6,
    authenticity: "原生",
    qualityScore: 94,
    checkedAt: "2026-04-26 10:30",
    notes: "函数调用、长上下文与拒答风格接近官方。",
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/leaderboard/",
  },
  {
    id: "eval-hvoy-gpt55",
    relayName: "禾维收录站点 B",
    model: "GPT-5.5",
    endpoint: "OpenAI Compatible",
    latencyMs: 214,
    availability: 98.7,
    waterRate: 1.4,
    authenticity: "待复测",
    qualityScore: 90,
    checkedAt: "2026-04-26 09:10",
    notes: "常规问答稳定，高并发下延迟波动。",
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/leaderboard/",
  },
  {
    id: "eval-hvoy-gemini",
    relayName: "禾维收录站点 C",
    model: "Gemini 3.1 Pro Preview",
    endpoint: "Gemini Compatible",
    latencyMs: 310,
    availability: 96.8,
    waterRate: 2.2,
    authenticity: "疑似路由",
    qualityScore: 82,
    checkedAt: "2026-04-25 22:40",
    notes: "部分安全策略与官方不完全一致，建议复测。",
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/",
  },
  {
    id: "eval-hvoy-qwen",
    relayName: "禾维收录站点 D",
    model: "Qwen3.6 Plus",
    endpoint: "OpenAI Compatible",
    latencyMs: 142,
    availability: 99.1,
    waterRate: 0.9,
    authenticity: "原生",
    qualityScore: 89,
    checkedAt: "2026-04-25 19:20",
    notes: "中文问答稳定，代码题需要关注上下文裁剪。",
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/leaderboard/",
  },
];

export const submissions: Submission[] = [
  {
    id: "sub-new-hub",
    siteName: "New API Hub",
    url: "https://example.com",
    categoryKey: "relay",
    reason: "支持 Claude、OpenAI、Gemini，提供测试额度。",
    contact: "user@example.com",
    status: "待审核",
    createdAt: "2026-04-26 11:20",
  },
  {
    id: "sub-ai-tools",
    siteName: "AI Tools Collection",
    url: "https://tools.example.com",
    categoryKey: "tool",
    reason: "聚合常用 AI 生产力工具。",
    status: "已通过",
    createdAt: "2026-04-25 15:03",
  },
];

export const dashboardStats: DashboardStats = {
  totalSites: 46,
  activeSites: 39,
  todayVisits: 12345,
  pendingSubmissions: 23,
};
