import type {
  Category,
  CodingPlan,
  DashboardStats,
  ModelPrice,
  ModelRanking,
  RelayEvaluation,
  Resource,
  SourceLink,
  Submission,
} from "./types";

export const sourceLinks: SourceLink[] = [
  {
    name: "知乎 Coding Plan 对比",
    url: "https://zhuanlan.zhihu.com/p/2015468530938693485",
    description: "国内外 AI Coding 订阅与额度口径参考。",
  },
  {
    name: "awesome-coding-plan",
    url: "https://github.com/mahonzhan/awesome-coding-plan",
    description: "Cursor、Claude Code、Trae、Qoder、Windsurf 等计划对比。",
  },
  {
    name: "LiteLLM model prices",
    url: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    description: "模型输入/输出价格与上下文窗口。",
  },
  {
    name: "Arena Leaderboard",
    url: "https://arena.ai/leaderboard",
    description: "用户偏好投票驱动的大模型榜单。",
  },
  {
    name: "SuperCLUE",
    url: "https://www.superclueai.com/generalpage",
    description: "中文大模型综合能力与应用能力榜单。",
  },
  {
    name: "禾维 AI",
    url: "https://www.hvoy.ai/leaderboard/",
    description: "中转站价格、延迟、在线率、掺水率与模型验证参考。",
  },
  {
    name: "AI 比价",
    url: "https://www.aibijia.org/",
    description: "ChatGPT、Gemini、Claude Code、Grok 等代充比价入口。",
  },
  {
    name: "TelegramGroup",
    url: "https://github.com/itgoyo/TelegramGroup",
    description: "Telegram 群组与频道导航开源集合。",
  },
];

export const categories: Category[] = [
  {
    id: "cat-coding",
    key: "coding",
    name: "Coding Plan 对比",
    description: "订阅价格、额度口径、模型倍率和 API 成本",
    iconName: "Code2",
    sortOrder: 1,
    count: 9,
  },
  {
    id: "cat-leaderboard",
    key: "leaderboard",
    name: "大模型排行",
    description: "Arena、SuperCLUE 与代码能力综合排序",
    iconName: "Trophy",
    sortOrder: 2,
    count: 10,
  },
  {
    id: "cat-relay",
    key: "relay",
    name: "中转站导航",
    description: "价格、在线率、延迟、掺水率和模型覆盖",
    iconName: "Network",
    sortOrder: 3,
    count: 8,
  },
  {
    id: "cat-topup",
    key: "topup",
    name: "代充站导航",
    description: "订阅代充、比价、服务范围和风险提示",
    iconName: "WalletCards",
    sortOrder: 4,
    count: 6,
  },
  {
    id: "cat-telegram",
    key: "telegram",
    name: "飞机频道导航",
    description: "AI 工具、开发、搜索与资源频道",
    iconName: "Send",
    sortOrder: 5,
    count: 7,
  },
  {
    id: "cat-validation",
    key: "validation",
    name: "模型验证评价",
    description: "中转站模型响应质量、原生度与稳定性记录",
    iconName: "ShieldCheck",
    sortOrder: 6,
    count: 6,
  },
];

export const resources: Resource[] = [
  {
    id: "res-hvoy",
    name: "禾维 AI 中转站排行榜",
    categoryKey: "relay",
    url: "https://www.hvoy.ai/leaderboard/",
    description: "按模型收录中转站价格、在线率、掺水率、延迟和运行状态。",
    tags: ["价格", "在线率", "掺水率", "延迟"],
    region: "国内",
    status: "active",
    score: 4.9,
    visits: 26800,
    latencyMs: 165,
    uptime: 99.3,
    waterRate: 0.6,
    pricingNote: "按模型与站点倍率展示",
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/leaderboard/",
    models: ["Claude", "GPT", "Gemini", "DeepSeek", "Qwen"],
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-hvoy-validation",
    name: "禾维 AI 模型验证",
    categoryKey: "validation",
    url: "https://www.hvoy.ai/",
    description: "对中转站模型进行可用性、原生度、延迟和质量复测。",
    tags: ["模型验证", "原生度", "质量评分"],
    region: "国内",
    status: "active",
    score: 4.8,
    visits: 15200,
    latencyMs: 178,
    uptime: 98.9,
    waterRate: 1.1,
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/",
    models: ["Claude Sonnet", "GPT-5.4", "Gemini Pro"],
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-litellm",
    name: "LiteLLM 模型价格库",
    categoryKey: "coding",
    url: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    description: "开源模型价格与上下文窗口数据库，适合做 API 价格基准。",
    tags: ["API 价格", "上下文", "开源"],
    region: "全球",
    status: "active",
    score: 4.9,
    visits: 18900,
    sourceName: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    models: ["OpenAI", "Anthropic", "Google", "DeepSeek", "Moonshot"],
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-awesome-coding",
    name: "awesome-coding-plan",
    categoryKey: "coding",
    url: "https://github.com/mahonzhan/awesome-coding-plan",
    description: "对比 Coding Agent 订阅计划、额度周期、模型倍率和性价比。",
    tags: ["Coding Agent", "订阅", "额度"],
    region: "全球",
    status: "active",
    score: 4.8,
    visits: 12600,
    sourceName: "GitHub",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-arena",
    name: "Arena Leaderboard",
    categoryKey: "leaderboard",
    url: "https://arena.ai/leaderboard",
    description: "基于用户偏好投票的文本、代码、推理模型榜单。",
    tags: ["Arena", "用户投票", "模型排行"],
    region: "海外",
    status: "active",
    score: 4.9,
    visits: 52200,
    sourceName: "Arena",
    sourceUrl: "https://arena.ai/leaderboard",
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-superclue",
    name: "SuperCLUE",
    categoryKey: "leaderboard",
    url: "https://www.superclueai.com/generalpage",
    description: "中文大模型综合能力、应用能力与多维评测榜单。",
    tags: ["中文评测", "综合能力", "应用能力"],
    region: "国内",
    status: "active",
    score: 4.6,
    visits: 30800,
    sourceName: "SuperCLUE",
    sourceUrl: "https://www.superclueai.com/generalpage",
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-aibijia",
    name: "AI 比价",
    categoryKey: "topup",
    url: "https://www.aibijia.org/",
    description: "聚合 ChatGPT、Gemini、Claude Code、Grok 等订阅代充比价。",
    tags: ["ChatGPT", "Gemini", "Claude Code", "Grok"],
    region: "国内",
    status: "active",
    score: 4.7,
    visits: 21300,
    pricingNote: "展示各服务商报价，交易前需自行核验",
    sourceName: "AI 比价",
    sourceUrl: "https://www.aibijia.org/",
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-telegramgroup",
    name: "TelegramGroup",
    categoryKey: "telegram",
    url: "https://github.com/itgoyo/TelegramGroup",
    description: "开源 Telegram 群组频道合集，覆盖搜索、资源、技术和工具分类。",
    tags: ["Telegram", "频道", "开源索引"],
    region: "全球",
    status: "active",
    score: 4.3,
    visits: 18100,
    sourceName: "TelegramGroup",
    sourceUrl: "https://github.com/itgoyo/TelegramGroup",
    verifiedAt: "2026-04-26",
  },
  {
    id: "res-soso",
    name: "soso 搜索机器人",
    categoryKey: "telegram",
    url: "https://t.me/soso",
    description: "Telegram 搜索入口，适合快速发现频道、群组和公开资源。",
    tags: ["搜索", "机器人", "频道发现"],
    region: "全球",
    status: "active",
    score: 4.1,
    visits: 8600,
    sourceName: "TelegramGroup",
    sourceUrl: "https://github.com/itgoyo/TelegramGroup",
  },
  {
    id: "res-technews",
    name: "科技圈的日常",
    categoryKey: "telegram",
    url: "https://t.me/kejijun",
    description: "科技资讯、AI 工具与开发者新闻频道。",
    tags: ["资讯", "AI 工具", "开发"],
    region: "全球",
    status: "active",
    score: 4.0,
    visits: 7200,
    sourceName: "TelegramGroup",
    sourceUrl: "https://github.com/itgoyo/TelegramGroup",
  },
];

export const codingPlans: CodingPlan[] = [
  {
    id: "plan-claude-code-max",
    vendor: "Claude Code",
    plan: "Max 5x",
    monthlyPrice: "$100 / 月",
    quota: "5 小时窗口约 900 条请求，约 2250 万 tokens",
    quotaType: "Usage-based",
    period: "5h",
    requests: "~900 / 5h",
    tokens: "~22.5M / 5h",
    monthlyValue: "$2,808",
    valueRatio: "28.1x",
    tps: "≈1250",
    includedModels: ["Claude Opus", "Claude Sonnet"],
    strengths: ["长上下文代码库理解", "终端 Agent 工作流", "复杂重构能力强"],
    bestFor: "复杂代码库、长期 Agent 编程和高强度开发",
    officialUrl: "https://www.anthropic.com/claude-code",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    score: 9.6,
  },
  {
    id: "plan-qoder-pro",
    vendor: "Qoder",
    plan: "Pro",
    monthlyPrice: "$20 / 月",
    quota: "积分制，Deep Think 与高阶模型按倍率消耗",
    quotaType: "Quota-based",
    period: "month",
    requests: "积分池",
    tokens: "随模型倍率",
    monthlyValue: "$708",
    valueRatio: "35.4x",
    tps: "按模型",
    includedModels: ["Claude Sonnet", "Gemini", "Qwen"],
    strengths: ["国产 IDE 适配", "计划性价比高", "模型池灵活"],
    bestFor: "国内开发者和多模型编码工作流",
    officialUrl: "https://qoder.com/",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    score: 9.2,
  },
  {
    id: "plan-cursor-pro",
    vendor: "Cursor",
    plan: "Pro",
    monthlyPrice: "$20 / 月",
    quota: "约 500 条快速高级请求，后台池按策略排队",
    quotaType: "Usage-based",
    period: "month",
    requests: "~500 fast",
    tokens: "按请求消耗",
    monthlyValue: "$240",
    valueRatio: "12x",
    tps: "稳定",
    includedModels: ["Claude Sonnet", "GPT-5", "Gemini"],
    strengths: ["IDE 生态成熟", "补全体验稳定", "团队协作好"],
    bestFor: "日常编码、重构和多人协作",
    officialUrl: "https://cursor.com/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    score: 9.0,
  },
  {
    id: "plan-trae-pro",
    vendor: "Trae",
    plan: "Pro",
    monthlyPrice: "$10 / 月",
    quota: "每月 600 条，部分模型按 0.5x 到 2x 消耗",
    quotaType: "Usage-based",
    period: "month",
    requests: "600 / 月",
    tokens: "按模型倍率",
    monthlyValue: "$162",
    valueRatio: "16.2x",
    tps: "中等",
    includedModels: ["Claude", "GPT", "Doubao"],
    strengths: ["价格低", "适合轻量项目", "中文环境友好"],
    bestFor: "预算敏感的个人开发者",
    officialUrl: "https://www.trae.ai/",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    score: 8.6,
  },
  {
    id: "plan-windsurf-pro",
    vendor: "Windsurf",
    plan: "Pro",
    monthlyPrice: "$15 / 月",
    quota: "Cascade 与高级模型按请求池消耗",
    quotaType: "Usage-based",
    period: "month",
    requests: "按请求池",
    tokens: "按模型倍率",
    monthlyValue: "$135",
    valueRatio: "9x",
    tps: "稳定",
    includedModels: ["Claude", "GPT", "SWE"],
    strengths: ["Agent 编程体验强", "项目级上下文", "价格友好"],
    bestFor: "希望以较低成本使用 Agent IDE 的个人开发者",
    officialUrl: "https://windsurf.com/pricing",
    sourceName: "awesome-coding-plan",
    sourceUrl: "https://github.com/mahonzhan/awesome-coding-plan",
    score: 8.5,
  },
  {
    id: "plan-api-direct",
    vendor: "API 直连",
    plan: "按量调用",
    monthlyPrice: "按模型计费",
    quota: "无固定月额度，成本由输入/输出 tokens 决定",
    quotaType: "API",
    period: "month",
    requests: "不限",
    tokens: "按量",
    monthlyValue: "透明",
    valueRatio: "取决于用量",
    tps: "受账户限额",
    includedModels: ["OpenAI", "Anthropic", "Gemini", "DeepSeek", "Kimi"],
    strengths: ["透明计费", "适合自研工具", "成本可精细控制"],
    bestFor: "有工程能力、需要自动化和成本控制的团队",
    officialUrl: "https://github.com/BerriAI/litellm",
    sourceName: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    score: 8.9,
  },
];

export const modelPrices: ModelPrice[] = [
  {
    id: "price-gpt-55",
    provider: "OpenAI",
    model: "GPT-5.5",
    inputUsdPer1M: 5,
    outputUsdPer1M: 30,
    context: "1,050K",
    maxOutput: "128K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-gpt-54",
    provider: "OpenAI / Azure",
    model: "GPT-5.4",
    inputUsdPer1M: 2.5,
    outputUsdPer1M: 15,
    context: "1,050K",
    maxOutput: "128K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-claude-opus-47",
    provider: "Anthropic / OpenRouter",
    model: "Claude Opus 4.7",
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    context: "1,000K",
    maxOutput: "128K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-claude-sonnet-46",
    provider: "Anthropic / OpenRouter",
    model: "Claude Sonnet 4.6",
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    context: "1,000K",
    maxOutput: "128K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-gemini-31",
    provider: "Google",
    model: "Gemini 3.1 Pro Preview",
    inputUsdPer1M: 2,
    outputUsdPer1M: 12,
    context: "1,048K",
    maxOutput: "65K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-kimi-k26",
    provider: "Moonshot",
    model: "Kimi K2.6",
    inputUsdPer1M: 0.95,
    outputUsdPer1M: 4,
    context: "262K",
    maxOutput: "262K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
  {
    id: "price-deepseek-v32",
    provider: "DeepSeek",
    model: "DeepSeek V3.2",
    inputUsdPer1M: 0.28,
    outputUsdPer1M: 0.42,
    context: "128K",
    maxOutput: "8K",
    source: "LiteLLM",
    sourceUrl: "https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json",
    updatedAt: "2026-04-26",
  },
];

export const modelRankings: ModelRanking[] = [
  {
    id: "rank-claude-opus-thinking",
    rank: 1,
    model: "Claude Opus 4.7 Thinking",
    provider: "Anthropic",
    arenaScore: 1503,
    codeScore: 1572,
    chineseScore: 92,
    reasoningScore: 97,
    context: "1M",
    source: "Arena",
    sourceUrl: "https://arena.ai/leaderboard",
    badge: "综合第一梯队",
  },
  {
    id: "rank-claude-opus-46",
    rank: 2,
    model: "Claude Opus 4.6",
    provider: "Anthropic",
    arenaScore: 1496,
    codeScore: 1545,
    chineseScore: 91,
    reasoningScore: 96,
    context: "1M",
    source: "Arena",
    sourceUrl: "https://arena.ai/leaderboard",
    badge: "代码强项",
  },
  {
    id: "rank-gemini-31",
    rank: 3,
    model: "Gemini 3.1 Pro Preview",
    provider: "Google",
    arenaScore: 1493,
    codeScore: 1468,
    chineseScore: 94,
    reasoningScore: 95,
    context: "1M",
    source: "综合",
    sourceUrl: "https://arena.ai/leaderboard",
    badge: "长上下文",
  },
  {
    id: "rank-gpt-55",
    rank: 4,
    model: "GPT-5.5",
    provider: "OpenAI",
    arenaScore: 1490,
    codeScore: 1501,
    chineseScore: 93,
    reasoningScore: 96,
    context: "1M",
    source: "Arena",
    sourceUrl: "https://arena.ai/leaderboard",
    badge: "推理稳定",
  },
  {
    id: "rank-qwen36",
    rank: 5,
    model: "Qwen3.6 Plus",
    provider: "阿里巴巴",
    arenaScore: 1471,
    codeScore: 1471,
    chineseScore: 96,
    reasoningScore: 92,
    context: "128K",
    source: "SuperCLUE",
    sourceUrl: "https://www.superclueai.com/generalpage",
    badge: "中文强项",
  },
  {
    id: "rank-kimi",
    rank: 6,
    model: "Kimi K2.6",
    provider: "月之暗面",
    arenaScore: 1466,
    codeScore: 1529,
    chineseScore: 95,
    reasoningScore: 91,
    context: "256K",
    source: "SuperCLUE",
    sourceUrl: "https://www.superclueai.com/generalpage",
    badge: "代码与中文",
  },
  {
    id: "rank-deepseek",
    rank: 7,
    model: "DeepSeek V3.2",
    provider: "DeepSeek",
    arenaScore: 1458,
    codeScore: 1463,
    chineseScore: 94,
    reasoningScore: 90,
    context: "128K",
    source: "综合",
    sourceUrl: "https://arena.ai/leaderboard",
    badge: "高性价比",
  },
];

export const relayEvaluations: RelayEvaluation[] = [
  {
    id: "eval-hvoy-claude-opus",
    relayName: "禾维收录站点 A",
    model: "Claude Opus 4.7",
    endpoint: "OpenAI Compatible",
    latencyMs: 168,
    availability: 99.3,
    waterRate: 0.6,
    authenticity: "原生",
    qualityScore: 94,
    checkedAt: "2026-04-26 10:30",
    notes: "函数调用、长上下文与拒答风格接近官方。",
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/leaderboard/",
  },
  {
    id: "eval-hvoy-gpt55",
    relayName: "禾维收录站点 B",
    model: "GPT-5.5",
    endpoint: "OpenAI Compatible",
    latencyMs: 214,
    availability: 98.7,
    waterRate: 1.4,
    authenticity: "待复测",
    qualityScore: 90,
    checkedAt: "2026-04-26 09:10",
    notes: "常规问答稳定，高并发下延迟波动。",
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/leaderboard/",
  },
  {
    id: "eval-hvoy-gemini",
    relayName: "禾维收录站点 C",
    model: "Gemini 3.1 Pro Preview",
    endpoint: "Gemini Compatible",
    latencyMs: 310,
    availability: 96.8,
    waterRate: 2.2,
    authenticity: "疑似路由",
    qualityScore: 82,
    checkedAt: "2026-04-25 22:40",
    notes: "部分安全策略与官方不完全一致，建议复测。",
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/",
  },
  {
    id: "eval-hvoy-qwen",
    relayName: "禾维收录站点 D",
    model: "Qwen3.6 Plus",
    endpoint: "OpenAI Compatible",
    latencyMs: 142,
    availability: 99.1,
    waterRate: 0.9,
    authenticity: "原生",
    qualityScore: 89,
    checkedAt: "2026-04-25 19:20",
    notes: "中文问答稳定，代码题需要关注上下文裁剪。",
    sourceName: "禾维 AI",
    sourceUrl: "https://www.hvoy.ai/leaderboard/",
  },
];

export const submissions: Submission[] = [
  {
    id: "sub-new-hub",
    siteName: "New API Hub",
    url: "https://example.com",
    categoryKey: "relay",
    reason: "支持 Claude、OpenAI、Gemini，提供测试额度。",
    contact: "user@example.com",
    status: "待审核",
    createdAt: "2026-04-26 11:20",
  },
  {
    id: "sub-ai-tools",
    siteName: "AI Tools Collection",
    url: "https://tools.example.com",
    categoryKey: "tool",
    reason: "聚合常用 AI 生产力工具。",
    status: "已通过",
    createdAt: "2026-04-25 15:03",
  },
];

export const dashboardStats: DashboardStats = {
  totalSites: 46,
  activeSites: 39,
  todayVisits: 12345,
  pendingSubmissions: 23,
};
